### ISSUE TITLE
Header dislodges from top when scrolling down and then scrolling back up

### ISSUE THREAD

**Issue by gvilarino** [arquitecturas-concurrentes/arquitecturas-concurrentes.github.io#2]
![screen shot 2015-07-17 at 4 25 13 pm](https://cloud.githubusercontent.com/assets/2538465/8755330/7747aa24-2ca0-11e5-81e5-9c0c3b27f987.png)

**Comment by bossiernesto** [comment]
Do you have the browser and version? I'm trying to reproduce in Chrome and Firefox in order to fix it. Thanks

**Comment by gvilarino** [comment]
Chrome 43.0.2357.134 (64-bit)

It happens in both incognito and regular browsing

**Comment by bossiernesto** [comment]
fixed this long time ago, but forgot to close this issue. In case this issue comes up again, please re-open this ticket or a new one.
